variables:
  PUBLISH_PATH: "/var/publish/$CI_PIPELINE_ID/"

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore
    - dotnet publish
  artifacts:
    expire_in: 1 days

test:
  stage: test
  script:
    - dotnet test --no-build --verbosity normal